name: kubernetes-client-helper
version: 0.1.0.0
library:
  source-dirs: src
license-file: ../LICENSE
dependencies:
  - base >=4.7 && <5.0
  - kubernetes == 0.1.0.0
  - pem >= 0.2.2 && <= 0.2.4
  - x509 >= 1.7.2 && <= 1.7.4
  - tls >= 1.4.0 && <= 1.4.1
  - x509-system == 1.6.6
  - x509-store >= 1.6.5 && <= 1.6.6
  - data-default-class >= 0.1.2 && < 0.1.3
  - connection >= 0.2.8 && < 0.2.9
  - x509-validation  >= 1.6.9 && <= 1.6.10
  - http-client >=0.5 && <0.6
  - http-client-tls >= 0.3.5.1 && <= 0.3.5.3
  - microlens >= 0.4.3 && <0.5
  - bytestring >=0.10.0 && <0.11
  - text >=0.11 && <1.3
  - safe-exceptions <0.2



